model_name: null
dtype: bfloat16
enable_gradient_checkpointing: true
ddp_size: 1
tp_size: 1
cp_size: 1
max_length_per_device: null
optimizer:
  lr: 5e-6
  weight_decay: 1e-2
max_grad_norm: 1.0
scheduler:
  name: cosine_with_min_lr
  min_lr: 5e-7
  warmup_ratio: 0.03
offload_optimizer: true